version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: loangauge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: cdac
      MYSQL_DATABASE: loangauge
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: loangauge-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
