server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/loangauge
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  mail:
    from: ${MAIL_FROM:noreply@loangauge.com}
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 900000        # 15 minutes
    refresh-token-expiration-ms: 604800000    # 7 days
  reset-token-expiration-ms: 900000           # 15 minutes
  frontend:
    reset-password-url: http://localhost:5173/reset-password
  refresh-token-cookie-name: refreshToken

internal:
  api-secret: ${INTERNAL_API_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method